const meta = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  domain: '',
  colors: {
    theme: '#161b21',
    status: 'black', // default | black | black-translucent
  },
  image: '',
  app: {
    id: '',
  },
};

export default meta;
